# NumPy  Practise

## NumPy Arrays

In [170]:
import numpy as np

### Creating NumPy Arrays

#### From Python list to NumPy Array

In [4]:
my_list = [1,2,3]

In [5]:
np.array(my_list) #Converts list to arrays 
                  #This is a 1D Array 

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat) #This is a 2D Array as it can be seen by the shape 
                 #and by the fact that there are 2 opening and closing square brackets

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Creaqting an Array from NumPy

In [10]:
#Common ways to create a numpy array 
np.arange(0,10) #10 is not included
#pass in a start,stop,step (a start pt, end pt and step size)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11) #this would give you a 1D array from 0-10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(0,11,2) #would give you all even numbers from 0-10

array([ 0,  2,  4,  6,  8, 10])

#### Creating an array with all Zeros

In [14]:
#generate all matrices of zeroes
np.zeros(3) #1 row and 3 columns

array([0., 0., 0.])

In [18]:
np.zeros((5,3)) #5 rows and 5 columns

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.zeros(((2,3,4))) #A 3D Array of all zeros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

#### Creating an array with all Ones

In [23]:
np.ones(3) #1D Matrix of all 1s

array([1., 1., 1.])

In [24]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### Cretaing an Array with elements being evenly spaced between start number and end number

In [26]:
#returns evenly spaced numbers form the start pt to the stop pt
np.linspace(0,5,10) #the parameters are start,stop, and the number of points 
                    #you want between the start and stop
#this is 1D Array as theres only 1 opening and closing []

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [28]:
np.linspace(0,10,5) #gives 5 evenly spaced numbers in between 0 and 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

#### Cretaing an Identity Matrix

In [29]:
#creating an identity matrix - diagonal of 1s and everything else is 0 and
#the number of rows = number of columns, therefore, it only takes in a 
#single digit as an argument!
np.eye(4) #This is a 2D array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Creating Arrays with Random Numbers as Elements

##### Elements - Uniform Distribution

In [31]:
#creating arrays of random numbers
np.random.rand(5) #creats an array of given shape and populate it with
                 #random numbers of uniform distribution between 0-1
#1D Array given

array([0.53707896, 0.33907259, 0.966611  , 0.64735446, 0.21558317])

In [32]:
np.random.rand(2,3) #pass in the dimensions

array([[0.2555671 , 0.01398327, 0.66463779],
       [0.50071626, 0.240412  , 0.4699979 ]])

##### Elements - Standard Normal Distirbution/Gaussian Distribution

In [36]:
np.random.randn(2) #numbers from the standard normal/gaussian distribution 
                   #and not uniform distribution
#Therefore it is not between 0 and 1.

array([1.383565  , 0.73399442])

In [37]:
np.random.randn(3,4)

array([[-0.09042559, -0.19703928,  0.40090048,  0.11006872],
       [-1.71374276,  0.2539941 ,  0.39745403, -1.17783139],
       [ 0.17892074, -1.33950352,  0.28505664,  0.27680224]])

##### Elements - Random Integers 

In [38]:
np.random.randint(1,100) #returns random integers from a low to high number
                        #3 the low number is inclusive but the high number is not

11

In [39]:
np.random.randint(1,100,10) #gives me a 1D Matrix of 10 randomly chosen 
                            #integers between 1 and 99.

array([79, 71, 93, 10, 21, 43, 19, 18, 87, 37])

##### Sidenote: It can also be written like this

In [78]:
from numpy.random import randint #instead of writing random.randint()

In [77]:
randint(2,10)

8

### Useful Methods of NumPy Arrays

#### Reshaping Arrays

In [41]:
arr = np.arange(25)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [67]:
arr.shape #is a 1D vector

(25,)

In [55]:
#reshape converts an existing array with a new arrray with the same data but diff dimensions
arr.reshape(5,5)
#you will get an error if you cant fill in the whole array
#CHECK = no. of rows * no of columns = no of total elements of the initial matirx

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [71]:
arr.shape #now it is a 2D Array

(5, 5)

#### Finding Min and Max Values in an Array

In [43]:
ranarr = np.random.randint(0,50,10)

In [45]:
ranarr

array([30, 37, 27, 33, 44, 18, 35, 17, 18, 13])

In [56]:
ranarr

array([30, 37, 27, 33, 44, 18, 35, 17, 18, 13])

In [60]:
ranarr.max() #returns the max value

44

In [61]:
ranarr.min() #returns the min value

13

#### Finding the position of the Min and Max Values in an Array

In [63]:
#finding the location of the max/min value in the array
ranarr.argmax() 
#therefore, 44 is located at the index location 4

4

In [65]:
ranarr.argmin()
#13 is the in the index position of 9

9

#### To find the Data Type of the elements in the Array

In [74]:
arr.dtype #the elements of the array are int32

dtype('int32')

### NumPy Array Indexing and Selection

#### Indexing and Slicing

In [80]:
arr = np.arange(0,11)

In [81]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
arr[8]

8

In [85]:
arr[1:5] #the end pt is not included

array([1, 2, 3, 4])

In [86]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [88]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [90]:
arr[5:]  #this grabs anything starting with the index 5

array([ 5,  6,  7,  8,  9, 10])

In [98]:
arr[0:5] 

array([0, 1, 2, 3, 4])

#### Making changes to the Array

In [99]:
arr[0:5] = 100 #this changes the first 5 elements to 100

In [100]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [101]:
#resetting the array
arr = np.arange(0,11)

In [102]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
slice_of_arr = arr[0:6] #taking a slice of the main array arr

In [105]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [106]:
slice_of_arr[:] = 99 #grabbing everything in that slice_of_arr

In [108]:
slice_of_arr #all the values are changed to 99

array([99, 99, 99, 99, 99, 99])

In [111]:
arr #the values of the main array are also changed

#therefore if you use slicing ie [x:y], to extract a part of the array,
#a copy of the main array is not being made, instead it is just a view of a
#part of the main array. Any changes done to the new variable will also be 
#reflected in the main array.

#Therefore, if you do want to extract a part of the array and work with 
#that part only, then, you have to actually make a copy using .copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [113]:
#resetting the array
arr = np.arange(0,11)

In [114]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
arr_copy = arr.copy()

In [116]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
arr_copy[:] = 100

In [118]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [119]:
arr #as observed the main array is not affected even if the copy was changed

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [122]:
arr_2d = np.array([[5,10,25],[20,25,30],[35,40,45]])

In [123]:
arr_2d

array([[ 5, 10, 25],
       [20, 25, 30],
       [35, 40, 45]])

#### Selecting Elements

##### Double Bracket Format

In [125]:
#grabbing elements using double bracket format
arr_2d[0][0] #grabbing the 5, [row index][col index]

5

In [127]:
arr_2d[0] #grabs the entire row

array([ 5, 10, 25])

In [130]:
arr_2d[1][1] #grabbing 25

25

In [131]:
arr_2d[2][1] #grabbing 40

40

##### Comma and Single Bracket Format

In [132]:
#using , single bracket notation
arr_2d[2,1] #grabbing 40 using the commar, single bracket notation

40

In [133]:
arr_2d[1,1] #[row index,column index]

25

In [136]:
arr_2d[:2]

array([[ 5, 10, 25],
       [20, 25, 30]])

In [135]:
arr_2d[:2,1:] 
#grab everything from begining to row 2(2 not included), AND from column 1
# till everything

array([[10, 25],
       [25, 30]])

#### Conditional Selection

In [143]:
# COnditional Selection
arr = np.arange(1,11)

In [144]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [147]:
#you can get an array of boolean values 
bool_arr = arr > 5

In [148]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [150]:
arr[bool_arr] #can return the bool_arr into the org array to get the numbers where you get true

array([ 6,  7,  8,  9, 10])

In [152]:
#doing all this in 1 step
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [153]:
arr[arr<3]

array([1, 2])

#### Extra Practise on Selecting Elements

In [155]:
arr_2d = np.arange(50).reshape(5,10)

In [156]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [164]:
sub_arr = arr_2d[1:3]

In [165]:
sub_arr

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [168]:
sub_arr = arr_2d[1:3,3:5]

In [169]:
sub_arr

array([[13, 14],
       [23, 24]])

## NumPy Operations

### Array with Array

In [171]:
arr = np.arange(0,11)

In [172]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [173]:
arr + arr #on an element-to-element basis

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [174]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [175]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [181]:
arr / arr #numpy gives u a warning, meaning you still get an output however
#in python, you get Zero division error, you get a NaN value as the first element

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [185]:
arr ** arr #each element raised ot the power of itself, 

array([         1,          1,          4,         27,        256,
             3125,      46656,     823543,   16777216,  387420489,
       1410065408], dtype=int32)

### Array with Scalars

In [177]:
arr + 100 

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [178]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [179]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [182]:
1 / arr # you get infifnity in the first term

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [183]:
arr ** 2 # each element is raised to the power of 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

### Universal Array Functions

In [187]:
np.sqrt(arr) #squareroot of each element

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [188]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [189]:
np.max(arr)

10

In [191]:
arr.max() #is the same thing as the prev cell

10

In [192]:
np.sin(arr) #sine of every element

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [193]:
np.cos(arr) #cosine of every element

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [195]:
np.tan(arr) #tangent of every element

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566,
        0.64836083])

In [196]:
np.log(arr) #log(0) is -infinity so you get a warning

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [199]:
np.remainder(arr,5) #returns the remainder when each element is divided by 5

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0], dtype=int32)